spring:
  application:
    name: msavaliadorcredito
  rabbitmq:
    port: 5672
    host: localhost
eureka:
  client:
    eureka-server-port: 8761
  instance:
    instance-id: ${spring.application.name}:${random.value}
server:
  port: 0

mq:
  queues:
    emissao-cartoes: emissao-cartoes