spring:
  application:
    name: eurekaserver
  security:
    user:
      name: user
      password: user

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
