spring:
  datasource:
    url: jdbc:h2:tcp://database:1521/testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  application:
    name: mscartoes
  rabbitmq:
    host: rabbitmq
    port: 5672
eureka:
  client:
    eureka-server-port: 8761
    service-url:
      defaultZone: eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
server:
  port: 0

mq:
  queues:
    emissao-cartoes: emissao-cartoes