spring:
  application:
    name: msclients

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://user:user@localhost:8761/eureka/
    eureka-server-port: 8761
  instance:
    instance-id: ${spring.application.name}:${random.value}