spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://eureka:8081/realms/mscourserealm
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: eureka
    fetch-registry: true
    register-with-eureka: true
    eureka-server-port: 8761
